# --- !Ups
CREATE SEQUENCE public.user_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;

CREATE TABLE public.user (
  id BIGINT NOT NULL DEFAULT nextval('user_id_seq'::regclass) PRIMARY KEY,
  firstname CHARACTER VARYING(20) NOT NULL,
  lastname CHARACTER VARYING(20) NOT NULL,
  mobile CHARACTER VARYING(20) NOT NULL,
  email CHARACTER VARYING(50) NOT NULL UNIQUE,
  age INTEGER NOT NULL
);

# --- !Downs
DROP TABLE public.user;
DROP SEQUENCE public.user_id_seq;

